services:
  postgres:
    image: postgres:15-alpine
    container_name: tasks-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - tasks_postgres_data:/var/lib/postgresql/data
    networks:
      - tasks-postgres-net

  api:
    build: ./tasks_api
    container_name: tasks-api
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      API_KEY: ${API_KEY}
      API_PORT: ${API_PORT}
      API_HOST: ${API_HOST}
    ports:
      - "8000:8000"
    volumes:
      - ./tasks_api:/app
    networks:
      - tasks-net
      - tasks-postgres-net

  bot:
    build: ./bot
    container_name: tasks-bot
    restart: unless-stopped
    depends_on:
      - api
    environment:
      API_PORT: ${API_PORT}
      API_HOST: api
      API_KEY: ${API_KEY}
      PROXY: ${PROXY}
      VLESS_PROXY: ${VLESS_PROXY}
      TOKEN: ${TOKEN}
    volumes:
      - ./bot:/app
    networks:
      - tasks-net

networks:
  tasks-net:
    driver: bridge
  tasks-postgres-net:
    driver: bridge

volumes:
  tasks_postgres_data:
    name: tasks-postgres-data