"""add columns due_date and visible_from, remove column date

Revision ID: af1dd9bf5160
Revises: 8a37200fd1f9
Create Date: 2026-03-06 12:57:11.713837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af1dd9bf5160'
down_revision: Union[str, Sequence[str], None] = '8a37200fd1f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('due_date', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('visible_from', sa.TIMESTAMP(timezone=True), nullable=True))
    op.drop_column('tasks', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'visible_from')
    op.drop_column('tasks', 'due_date')
    # ### end Alembic commands ###
