""""add table named folders"

Revision ID: b57cdce94218
Revises: e14a200bcac2
Create Date: 2026-02-21 04:48:50.145852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b57cdce94218'
down_revision: Union[str, Sequence[str], None] = 'e14a200bcac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tasks', sa.Column('folder_id', sa.Integer(), nullable=True))
    op.create_foreign_key("f_k_t_f_f_id_t_f_id", 'tasks', 'folders', ['folder_id'], ['id'])
    # op.create_unique_constraint("u_u_l", 'users', ['login'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint("u_u_l", 'users', type_='unique')
    op.drop_constraint("f_k_t_f_f_id_t_f_id", 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'folder_id')
    op.drop_table('folders')
    # ### end Alembic commands ###
