"""add show_progress column to table named folders

Revision ID: c357fb2e2c6f
Revises: b57cdce94218
Create Date: 2026-02-22 06:45:30.471940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c357fb2e2c6f'
down_revision: Union[str, Sequence[str], None] = 'b57cdce94218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folders', sa.Column('show_progress', sa.Boolean()))
    op.create_unique_constraint("u_u_l", 'users', ['login'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("u_u_l", 'users', type_='unique')
    op.drop_column('folders', 'show_progress')
    # ### end Alembic commands ###
