"""add columns for recurrence to table tasks

Revision ID: d8897ca4c3a0
Revises: c357fb2e2c6f
Create Date: 2026-03-02 15:05:21.258502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8897ca4c3a0'
down_revision: Union[str, Sequence[str], None] = 'c357fb2e2c6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('recurrence_type', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('recurrence_time', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('recurrence_day_of_week', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('recurrence_month_day', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('next_run', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'recurrence_month_day')
    op.drop_column('tasks', 'recurrence_day_of_week')
    op.drop_column('tasks', 'recurrence_time')
    op.drop_column('tasks', 'recurrence_type')
    op.drop_column('tasks', 'next_run')
    # ### end Alembic commands ###
