"""sync with orm models

Revision ID: e14a200bcac2
Revises: 6726fa349235
Create Date: 2026-02-14 12:37:15.382783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e14a200bcac2'
down_revision: Union[str, Sequence[str], None] = '6726fa349235'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_tasks_user_id_date'), table_name='tasks')
    op.drop_constraint(op.f('u_l_u'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('u_l_u'), 'users', ['login'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_tasks_user_id_date'), 'tasks', ['user_id', 'date'], unique=False)
    # ### end Alembic commands ###
